--
-- PostgreSQL database dump
--

\restrict AQpLLbjCO0AuYcUNS48jpuiCmYaU83aEi3ZAbV7YHIgJmtBwKBhggzvFm4cpyx5

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-09-04 12:45:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16531)
-- Name: pae; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA pae;


ALTER SCHEMA pae OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16533)
-- Name: curso; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.curso (
    id_curso bigint NOT NULL,
    id_jornada bigint NOT NULL,
    nombre_curso character varying(50) NOT NULL
);


ALTER TABLE pae.curso OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16532)
-- Name: curso_id_curso_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.curso ALTER COLUMN id_curso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.curso_id_curso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16542)
-- Name: entrega_racion; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.entrega_racion (
    id_entrega bigint NOT NULL,
    id_plan bigint NOT NULL,
    raciones_servidas integer NOT NULL
);


ALTER TABLE pae.entrega_racion OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16541)
-- Name: entrega_racion_id_entrega_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.entrega_racion ALTER COLUMN id_entrega ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.entrega_racion_id_entrega_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16551)
-- Name: estudiante; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.estudiante (
    id_estudiante bigint NOT NULL,
    documento_identidad character varying(20) NOT NULL,
    id_curso bigint NOT NULL,
    nombre_completo character varying(150) NOT NULL
);


ALTER TABLE pae.estudiante OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16550)
-- Name: estudiante_id_estudiante_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.estudiante ALTER COLUMN id_estudiante ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.estudiante_id_estudiante_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16561)
-- Name: insumo; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.insumo (
    id_insumo bigint NOT NULL,
    dias_entrega_proveedor integer NOT NULL,
    gramos_por_racion double precision NOT NULL,
    nombre_insumo character varying(100) NOT NULL,
    stock_inicial_configurado double precision NOT NULL,
    stock_reserva double precision NOT NULL,
    unidad_medida character varying(20) NOT NULL
);


ALTER TABLE pae.insumo OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16560)
-- Name: insumo_id_insumo_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.insumo ALTER COLUMN id_insumo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.insumo_id_insumo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16574)
-- Name: jornada; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.jornada (
    id_jornada bigint NOT NULL,
    nombre_jornada character varying(50) NOT NULL
);


ALTER TABLE pae.jornada OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16573)
-- Name: jornada_id_jornada_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.jornada ALTER COLUMN id_jornada ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.jornada_id_jornada_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16582)
-- Name: movimiento_insumo; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.movimiento_insumo (
    id_movimiento bigint NOT NULL,
    cantidad_recibida_kg double precision NOT NULL,
    consumo_del_dia_kg double precision NOT NULL,
    fecha date NOT NULL,
    id_insumo bigint NOT NULL,
    stock_inicial_kg double precision NOT NULL
);


ALTER TABLE pae.movimiento_insumo OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16581)
-- Name: movimiento_insumo_id_movimiento_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.movimiento_insumo ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.movimiento_insumo_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16594)
-- Name: personal_cocina; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.personal_cocina (
    id_personal bigint NOT NULL,
    id_turno bigint NOT NULL,
    nombre_completo character varying(150) NOT NULL,
    raciones_por_hora_capacidad double precision NOT NULL
);


ALTER TABLE pae.personal_cocina OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16593)
-- Name: personal_cocina_id_personal_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.personal_cocina ALTER COLUMN id_personal ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.personal_cocina_id_personal_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16604)
-- Name: plan_racion; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.plan_racion (
    id_plan bigint NOT NULL,
    costo_faltante_unitario double precision NOT NULL,
    costo_produccion_unitario double precision,
    costo_sobrante_unitario double precision NOT NULL,
    fecha date NOT NULL,
    id_curso bigint NOT NULL,
    margen_seguridad_usado double precision,
    matricula_total_registrada bigint NOT NULL,
    raciones_planificadas integer NOT NULL,
    tasa_asistencia_estimada double precision NOT NULL
);


ALTER TABLE pae.plan_racion OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16603)
-- Name: plan_racion_id_plan_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.plan_racion ALTER COLUMN id_plan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.plan_racion_id_plan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16618)
-- Name: turno; Type: TABLE; Schema: pae; Owner: postgres
--

CREATE TABLE pae.turno (
    id_turno bigint NOT NULL,
    horas_duracion double precision NOT NULL,
    nombre_turno character varying(50) NOT NULL
);


ALTER TABLE pae.turno OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16617)
-- Name: turno_id_turno_seq; Type: SEQUENCE; Schema: pae; Owner: postgres
--

ALTER TABLE pae.turno ALTER COLUMN id_turno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pae.turno_id_turno_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5067 (class 0 OID 16533)
-- Dependencies: 221
-- Data for Name: curso; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.curso (id_curso, id_jornada, nombre_curso) FROM stdin;
1	1	1A
2	1	1B
3	2	6A
4	1	2A
5	3	Grado 602
\.


--
-- TOC entry 5069 (class 0 OID 16542)
-- Dependencies: 223
-- Data for Name: entrega_racion; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.entrega_racion (id_entrega, id_plan, raciones_servidas) FROM stdin;
1	2	9
2	10	10
\.


--
-- TOC entry 5071 (class 0 OID 16551)
-- Dependencies: 225
-- Data for Name: estudiante; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.estudiante (id_estudiante, documento_identidad, id_curso, nombre_completo) FROM stdin;
1	1001	1	Ana Torres
2	1002	1	Luis Gomez
3	1003	1	Maria Perez
4	1004	1	Carlos Ruiz
5	1005	1	Sofia Diaz
6	1006	1	Juan Rojas
7	1007	1	Laura Vega
8	1008	1	Pedro Leon
9	1009	1	Diana Cruz
10	1010	1	Andres Paz
11	2001	4	Camilo Ruiz
12	1005188927	5	Ana Maria Mendoza
\.


--
-- TOC entry 5073 (class 0 OID 16561)
-- Dependencies: 227
-- Data for Name: insumo; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.insumo (id_insumo, dias_entrega_proveedor, gramos_por_racion, nombre_insumo, stock_inicial_configurado, stock_reserva, unidad_medida) FROM stdin;
1	3	80	Arroz Blanco	100	20	kg
2	2	250	Leche Entera	100	25	L
3	2	100	Pechuga de Pollo	80	15	kg
4	1	60	Verduras Mixtas	60	15	kg
5	2	60	Frijoles	80	15	kg
\.


--
-- TOC entry 5075 (class 0 OID 16574)
-- Dependencies: 229
-- Data for Name: jornada; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.jornada (id_jornada, nombre_jornada) FROM stdin;
1	Mañana
2	Tarde
3	Mañana
\.


--
-- TOC entry 5077 (class 0 OID 16582)
-- Dependencies: 231
-- Data for Name: movimiento_insumo; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.movimiento_insumo (id_movimiento, cantidad_recibida_kg, consumo_del_dia_kg, fecha, id_insumo, stock_inicial_kg) FROM stdin;
1	0	2.5	2026-09-04	2	100
2	50	4.64	2026-09-04	1	100
3	20	5.8	2026-09-04	3	80
4	50	7.12	2026-09-04	1	145.36
\.


--
-- TOC entry 5079 (class 0 OID 16594)
-- Dependencies: 233
-- Data for Name: personal_cocina; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.personal_cocina (id_personal, id_turno, nombre_completo, raciones_por_hora_capacidad) FROM stdin;
1	1	Chef Ana	50
2	1	Hernesto	25
\.


--
-- TOC entry 5081 (class 0 OID 16604)
-- Dependencies: 235
-- Data for Name: plan_racion; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.plan_racion (id_plan, costo_faltante_unitario, costo_produccion_unitario, costo_sobrante_unitario, fecha, id_curso, margen_seguridad_usado, matricula_total_registrada, raciones_planificadas, tasa_asistencia_estimada) FROM stdin;
1	4350	4350	1305	2026-09-04	1	0.007	10	10	0.9
2	4350	4350	1305	2026-09-04	1	0.007	10	10	0.9
3	4350	4350	1305	2026-09-04	1	0.007	10	10	0.9
4	4350	4350	1305	2026-09-04	1	0.007	10	10	0.9
5	4350	4350	1305	2026-09-04	1	0.007	10	10	0.9
6	4350	4350	1305	2026-09-04	1	0.007	10	8	0.67
7	4350	4350	1305	2026-09-04	1	0.007	10	10	0.9
8	4350	4350	1305	2026-09-04	1	0.007	10	6	0.64
9	4350	4350	1305	2026-09-04	1	0.007	10	5	0.51
10	4350	4350	1305	2026-09-04	1	0.007	10	10	0.9
\.


--
-- TOC entry 5083 (class 0 OID 16618)
-- Dependencies: 237
-- Data for Name: turno; Type: TABLE DATA; Schema: pae; Owner: postgres
--

COPY pae.turno (id_turno, horas_duracion, nombre_turno) FROM stdin;
1	5	Manana
\.


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 220
-- Name: curso_id_curso_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.curso_id_curso_seq', 5, true);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 222
-- Name: entrega_racion_id_entrega_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.entrega_racion_id_entrega_seq', 2, true);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 224
-- Name: estudiante_id_estudiante_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.estudiante_id_estudiante_seq', 12, true);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 226
-- Name: insumo_id_insumo_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.insumo_id_insumo_seq', 5, true);


--
-- TOC entry 5093 (class 0 OID 0)
-- Dependencies: 228
-- Name: jornada_id_jornada_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.jornada_id_jornada_seq', 3, true);


--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 230
-- Name: movimiento_insumo_id_movimiento_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.movimiento_insumo_id_movimiento_seq', 4, true);


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 232
-- Name: personal_cocina_id_personal_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.personal_cocina_id_personal_seq', 2, true);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 234
-- Name: plan_racion_id_plan_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.plan_racion_id_plan_seq', 10, true);


--
-- TOC entry 5097 (class 0 OID 0)
-- Dependencies: 236
-- Name: turno_id_turno_seq; Type: SEQUENCE SET; Schema: pae; Owner: postgres
--

SELECT pg_catalog.setval('pae.turno_id_turno_seq', 1, true);


--
-- TOC entry 4898 (class 2606 OID 16540)
-- Name: curso curso_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.curso
    ADD CONSTRAINT curso_pkey PRIMARY KEY (id_curso);


--
-- TOC entry 4900 (class 2606 OID 16549)
-- Name: entrega_racion entrega_racion_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.entrega_racion
    ADD CONSTRAINT entrega_racion_pkey PRIMARY KEY (id_entrega);


--
-- TOC entry 4904 (class 2606 OID 16559)
-- Name: estudiante estudiante_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.estudiante
    ADD CONSTRAINT estudiante_pkey PRIMARY KEY (id_estudiante);


--
-- TOC entry 4908 (class 2606 OID 16572)
-- Name: insumo insumo_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.insumo
    ADD CONSTRAINT insumo_pkey PRIMARY KEY (id_insumo);


--
-- TOC entry 4910 (class 2606 OID 16580)
-- Name: jornada jornada_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.jornada
    ADD CONSTRAINT jornada_pkey PRIMARY KEY (id_jornada);


--
-- TOC entry 4912 (class 2606 OID 16592)
-- Name: movimiento_insumo movimiento_insumo_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.movimiento_insumo
    ADD CONSTRAINT movimiento_insumo_pkey PRIMARY KEY (id_movimiento);


--
-- TOC entry 4914 (class 2606 OID 16602)
-- Name: personal_cocina personal_cocina_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.personal_cocina
    ADD CONSTRAINT personal_cocina_pkey PRIMARY KEY (id_personal);


--
-- TOC entry 4916 (class 2606 OID 16616)
-- Name: plan_racion plan_racion_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.plan_racion
    ADD CONSTRAINT plan_racion_pkey PRIMARY KEY (id_plan);


--
-- TOC entry 4918 (class 2606 OID 16625)
-- Name: turno turno_pkey; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.turno
    ADD CONSTRAINT turno_pkey PRIMARY KEY (id_turno);


--
-- TOC entry 4902 (class 2606 OID 16627)
-- Name: entrega_racion uk7uhapuxr1ifq88fmmgrpan1fl; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.entrega_racion
    ADD CONSTRAINT uk7uhapuxr1ifq88fmmgrpan1fl UNIQUE (id_plan);


--
-- TOC entry 4906 (class 2606 OID 16629)
-- Name: estudiante ukr2nuqxx244iif8817ekh3dqag; Type: CONSTRAINT; Schema: pae; Owner: postgres
--

ALTER TABLE ONLY pae.estudiante
    ADD CONSTRAINT ukr2nuqxx244iif8817ekh3dqag UNIQUE (documento_identidad);


-- Completed on 2026-09-04 12:45:07

--
-- PostgreSQL database dump complete
--

\unrestrict AQpLLbjCO0AuYcUNS48jpuiCmYaU83aEi3ZAbV7YHIgJmtBwKBhggzvFm4cpyx5

